repos:

  -   repo: https://github.com/jvstein/pre-commit-dotnet-format
      rev: 'v0.2'
      hooks:
      -   id: dotnet-format

  -   repo: local
      hooks:
      -   id: dotnet-format
          name: dotnet-format FireboltDotNetSdk.sln
          entry: dotnet dotnet-format
          language: system
      -   id: style-cop-analyzer
          name: style-cop-analyzer
          entry: dotnet style check FireboltDotNetSdk.sln
          language: system

