name: Code quality checks

on:
  workflow_call:
  push:
    branches: [ main ]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Set up .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0

    - name: Run pre-commit checks
      uses: pre-commit/action@v2.0.3
